services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://mongodb:27017/patas-arriba

  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.runCommand('ping').ok" --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
