#!/usr/bin/env bash
# Harness constraint enforcement — generic CI fallback.
#
# Generated by the harness-engineering plugin.
# Run this script in any CI system to enforce PR-scoped constraints.
#
# Usage: bash scripts/ai-literacy-check.sh
#
# Inspired by Birgitta Boeckeler's "Harness Engineering":
# https://martinfowler.com/articles/exploring-gen-ai/harness-engineering.html

set -euo pipefail

HARNESS_FILE=".claude/HARNESS.md"

if [ ! -f "$HARNESS_FILE" ]; then
  echo "[harness] No $HARNESS_FILE found — skipping constraint enforcement"
  exit 0
fi

echo "[harness] Checking PR-scoped constraints from $HARNESS_FILE..."

# Placeholder: deterministic tool invocations are added here by
# /harness-constrain as constraints are promoted from unverified to
# deterministic.
#
# Example:
#   echo "[harness] Constraint: Consistent formatting"
#   npx prettier --check "client/src/**/*.{js,jsx,ts,tsx}"

echo "[harness] All constraints checked. See $HARNESS_FILE for details."
